rsp-cxd4: Update to commit 27ee22f.
https://github.com/mupen64plus/mupen64plus-rsp-cxd4/commit/27ee22f

*   27ee22f Merge pull request #27 from loganmc10/patch-1
|\
| * f2b5068 set SP_STATUS bits before calling ProcessDList
|/
*   3252841 Merge pull request #26 from gizmo98/remove-deprecated-sse3-option
|\
| * cbccfb8 Makefile: remove SSSE3 build option
|/
*   664759f Merge pull request #24 from loganmc10/patch-2
|\
| * 296ff10 Remove NBA on NBC setting
* |   13ef15a Merge pull request #25 from loganmc10/patch-3
|\ \
| |/
|/|
| * e83f768 Allow Rogue Squadron to run in HLE GFX
|/
* 0ceb539 Revert "Allow using compiler other than gcc"
*   933deaf Merge pull request #19 from loganmc10/hle
|\
| * 723fd79 Use HLE video by default if HLEVIDEO is set
* |   303f397 Merge pull request #20 from loganmc10/lle_list
|\ \
| * | 3e427db Force semaphore lock for NBA showtime
| * | 0c16b5a Allow the semaphore hack to try without full LLE.
| * | 33dae34 Force LLE graphics on ROMs known to require it
| |/
* |   6aa2bdd Merge pull request #21 from gizmo98/neon
|\ \
| * | d985730 add upstream change
| * | d7d50b5 move -mstackrealign to platform x86
| * | 89fdf16 Makefile: add arm neon option
| |/
* |   ca59ef5 Merge pull request #22 from loganmc10/patch-1
|\ \
| |/
|/|
| * eae6112 Allow using compiler other than gcc
|/
*   3e3fa9b Merge pull request #18 from fzurita/master
|\
| * d253a75 Add rsp_api_exports.ver file
* |   bb48229 Merge pull request #17 from fzurita/libretro_neon
|\ \
| |/
|/|
| * 97d0e11 Restore some mupen64plus specific functionality
| * cc6b883 Add libretro NEON optimizations
|/
*   c904e8f Merge pull request #16 from charlemagnelasse/upstream-updates
|\
| *   136d15a Merge branch 'master' of https://github.com/cxd4/rsp into upstream-updates
| |\
| | * 8de7c0c Prefer to use GET_RSP_INFO().
| | * 5af7b5a Remove extra check before calling RDP lists.
| | * 7fc5768 Non-Windows builds should pause, too, on errors.
| | * 837d40b Update su.c
| | * 20f4758 rephrased immediate signedness decoder in SLTI[U]
| | * 69ae479 fixed LP64 segfault in LSV
| | * f0e79aa fixed all discoverable warnings on the current platform
| | * 34f17d1 fixed rest of the set-but-never-used warnings
| | * 00ac765 warning:  parameter hParent set but not used [-Wunused-but-set-parameter]
| | * c0722d3 warning:  redundant redeclaration of (blah) [-Wredundant-decls]
| | * 2d04d36 fixed remaining strict -Wshadow warning messages
| | * e9edb92 warning: declaration of inst shadows a global declaration [-Wshadow]
| | * c3dd4c5 Assimilate from newer cxd4/rcp64/my_types.h.
| | * a6c5118 style fixes
| | * 9cf9089 Remove the pointer relation requirement between DMEM and IMEM.
| | * 88b125f warning:  overflow in implicit constant conversion [-Woverflow]
| | * 653d9ca Consolidate x86_64 vs. x86_32 for automation.
| | * f95937a Remove DPC_CLR_FREEZE spamming for non-PJ64 emulators.
| | * 32b939f moved MFC0 SP_STATUS timer counts outside to DoRspCycles
| | * d44b446 moved task recovery and scheduling outside to DoRspCycles
| | * cd5aae0 deleted old, unused source[] and target[] temp vectors
| | * 816be99 deleted my old `vector_op` function pointer experiment
| | * 06586a4 Instead of PINSRW, try non-SSE for a pre-buffer.
| | * 7d9a42c Prevent in-line expansion of function `do_div()`.
| | * a1c5398 Make sure the RCP division ROM constants parse as unsigned.
| | * 730deb7 finished restoring old VU scheduler optimizations
| | * 4618eca removed extra debugging statement I used while testing
| | * 243d41f restored quarter-scalar vector optimizations
| | * be090aa deleted global variable CPU_running
| | * 04e20c4 removed unnecessary SP_STATUS_HALT constant CPU loop checks
| | * e4bf8b3 Delete the inline function:  R4000_fetch_decode_execute().
| | * 8d2e63d Restore in-lined state to scalar vector ops.
| | * d888e2a Restore in-lined state to plain vector ops.
| | * 51f0c76 USE_CLIENT_ENDIAN:  Do not depend on TRUE/FALSE #define's.
| | * 639b987 new IW_RD() #define to restore missing rd decode micro-opt.
| | * 71356b7 deleted VMACQ from the function table
| | * e79c29a Disable vector operation name-mangling macros for WIN32.
| | * 14dfd31 ~1.2% speed gain from not using LUT for shuffling
| | * b6ed42a rewrote the vector register aliasing stuff
| | * 7e7d380 more security to prevent falsely optimizing SPECIAL_DECODE_RS()
| | * f275dbd fixed risky pre-processor detection of 32-bit SA support
| | * 0934271 deleted old sign- and zero-extension macro functions
| | * fe559e7 Use char, not uint8_t, to satisfy strict aliasing rules.
| | * b9f3593 SR_B() #define:  (extraneous (layers of (parenthesis)))
| | * 88ffa32 moved the MMX recovery stuff out of SU unit to task dispatcher
| | * c41883e caught some remaining missed uses for FIT_IMEM()
| | * 4ae03a2 restored old LW micro-optimizations using SR_B() macro
| | * 4f25101 Try, yet again, to make GitHub not parse divide.h as C++.
| | * 6b96e7e restored old SH and SW optimizations using SR_B() macro
| | * a4a7869 rewrote COP2 to its own function for profiling/debugging
| | * f9e20f9 rewrote COP0 to its own function for profiling/debugging
| | * 3675adb rewrote REGIMM to a separate function for profiling/debugging
| | * d41ab3c rewrote LWC2 and SWC2
| | * b6d69ec rewrote SPECIAL to its own function for profiling/debugging
| | * cbf49ef rewrote J and JAL
| | * 4ccd6e8 a few more trivial clean-ups
| | * 5acda69 rewrote BEQ, BNE, BLEZ and BGTZ
| | * 4e31a8c Try to stop GitHub from parsing this header as C++.
| | * bdf9e27 rewrote ADDI[U], SLTI and SLTIU
| | * f790f49 For bit-wise portability, GPR file should not be signed.
| | * 3760de8 rewrote ANDI, ORI, XORI and LUI
| | * abf4981 Enumerate the list of GPR assembler syntax names.
| | * f9579c1 rewrote LB, LBU, LH, LHU, LW, SB, SH and SW
| | * 0cb4e5a #define PROFILE_MODE to prefer speed vs. benchmark precision
| | * 43ef2e2 split R4000 CPU interpreter cycle to its own function
| | * aad3ecf CONTINUE macro #define should be deleted.
| | * 776e50d EMULATE_STATIC_PC #define moved to header
| | * f74c9fe message():  standard codespace braces conformance
| | * 3941c64 Do not always allocate a 4096-byte message buffer.
| | * f503209 accurate VSAR IW decoding of valid, scalar-based elements
| | * d807c78 some trivial clean-ups
| | * f939466 Delay the AND mask step adjusting to Mupen64's lack of one.
| | * 8a37d06 cleaned up step_SP_commands()
| | * c7142b5 Diagnose GlobalFree() in case it ever fails.
| | * b23bc4c The comment on GetModulePath() PJ64 2.0 hack isn't relevant.
| | *   898e380 Merge pull request #5 from cxd4/HVQM
| | |\
| | | * 7afdfb9 Force refreshing color buffer in case the VI module neglects to.
| | |/
| | * 50190ff rewrote task scheduler read from memory
| | * 7323251 fixed broken GitHub markdown :)
| | * d68bcc4 Remove a (long since) outdated prototype.
| | * cd7c414 For better PIC linkage, remove SHUFFLE_VECTOR.
| | * 3d415f9 minor typo in the case-insensitive Win32 build scripts
| | * 7fb9850 fixed possible PIC linkage faults by moving `merge` to static
| | * 7d9e2fc Force invocation paths to bypass POSIX/Win32 shell install.
| | * 7310144 undefined reference to `memcpy` caused by compiling -O3 module.c
| | * 87b3d4c Start using a .gitignore after 4 years of needing one.
| | * c615b81 added 64-bit build script for Windows, since MinGW is 32-bit only
| | * bf7c98f Conker's BFD micro-optimization with 2's cmpl. integer division
| | * 690bb76 Do the same commit as before, but with `rt'/`vt'.
| | * 526d262 Do the same commit as before, but for `rs'/`vs' this time.
| | * fcde75a Optimize register allocation and timing:  Do not set rd globally.
| | * dede051 MinGW ld.exe doesn't always memorize standard library paths.
| | * 785b3f8 Some versions of Windows command shell might not like forward slashes.
* |   671d43d Merge pull request #15 from charlemagnelasse/travis-container
|\ \
| * | 199bf0e Use faster container based Travis CI
| |/
* | 16f28de Merge pull request #14 from charlemagnelasse/master
|/
* c06ec03 Use Ubuntu Trusty as base system for Travis CI